package:
  name: expipe-browser
  version: {{ environ.get("GIT_TAG", "0.0.0_custom")|replace("v", "")|replace("-", "_") }}

build:
  # noarch: python  # TODO Add back noarch when it works properly on Windows,
                    # we are converting packages manually now
  script: python setup.py install
  entry_points:
    - expipe-browser = expipebrowser.main:main
  
source:
  path: .

requirements:
  build:
    - python
    - setuptools
    - pip
    - numpy
    - quantities
    - pyyaml
    # - pyqt >=5 # TODO add this back when PyQt is delivered by conda-forge

  run:
    - python
    - setuptools
    - pip
    - numpy
    - scipy
    - quantities
    - pyyaml
    - exdir
    - expipe
    - pyqt >=5

test:
  imports:
    - expipebrowser

about:
  home: https://github.com/CINPLA/expipe-browser/
  license: GPLv3
  license_file: LICENSE
