package:
  version: {{ environ.get("GIT_DESCRIBE", "unknown_version")|replace("v", "")|replace("-", "_") }}
  
source:
  path: .

requirements:
  build:
    - python
    - setuptools
    - pip
    - numpy
    - quantities
    - pyyaml
    - pyqt

  run:
    - python
    - setuptools
    - pip
    - numpy
    - scipy
    - quantities
    - pyyaml
    - exdir
    - expipe

test:
  imports:
    - expipebrowser

about:
  home: https://github.com/CINPLA/expipe-browser/
  license: GPLv3
  license_file: LICENSE
